config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/contact'

  get 'products/index'
  get 'products/tango_drones'
  get 'products/tango_drones/hamilton'
  get 'products/tango_drones/eigen'
  get 'products/tango_drones/hoodlum'
  get 'products/tango_drones/hammer'
  get 'products/batteries'
  get 'products/motors'
  get 'products/escs'
  get 'products/propellers'
  resources :orders

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  end

  def tango_drones
  end

  def batteries
    @products = [
     {
       "voltage": 4,
       "current_rating": 15,
       "capacity": 5200,
       "item_number": "TA-15C-5200-4S1P-XT60",
       "ma_price": "$47.19",
       "list_price": "$47.19"
     },
     {
       "voltage": 6,
       "current_rating": 15,
       "capacity": 7000,
       "item_number": "TA-15C-7000-6S1P",
       "ma_price": "$79.99",
       "list_price": "$79.99"
     },
     {
       "voltage": 6,
       "current_rating": 15,
       "capacity": 8000,
       "item_number": "TA-15C-8000-6S1P-XT60",
       "ma_price": "$141.98",
       "list_price": "$141.98"
     },
     {
       "voltage": 6,
       "current_rating": 15,
       "capacity": 12000,
       "item_number": "TA-PLUS-15C-12000-6S1P-AS150",
       "ma_price": "$263.99",
       "list_price": "$263.99"
     },
     {
       "voltage": 6,
       "current_rating": 15,
       "capacity": 12000,
       "item_number": "TA-15C-12000-6S1P-XT90",
       "ma_price": "$260.63",
       "list_price": "$260.63"
     },
     {
       "voltage": 6,
       "current_rating": 15,
       "capacity": 12000,
       "item_number": "TA-15C-12000-6S1P-AS150",
       "ma_price": "$260.63",
       "list_price": "$260.63"
     },
     {
       "voltage": 6,
       "current_rating": 15,
       "capacity": 12000,
       "item_number": "TA-15C-12000-6S1P-EC5",
       "ma_price": "$260.63",
       "list_price": "$260.63"
     },
     {
       "voltage": 6,
       "current_rating": 15,
       "capacity": 12000,
       "item_number": "TA-PLUS-15C-12000-6S1P-EC5",
       "ma_price": "$263.99",
       "list_price": "$263.99"
     },
     {
       "voltage": 4,
       "current_rating": 15,
       "capacity": 16000,
       "item_number": "TA-15C-16000-4S1P",
       "ma_price": "$231.67",
       "list_price": "$231.67"
     },
     {
       "voltage": 6,
       "current_rating": 15,
       "capacity": 16000,
       "item_number": "TA-PLUS-15C-16000-6S1P-AS150",
       "ma_price": "$339.99",
       "list_price": "$339.99"
     },
     {
       "voltage": 6,
       "current_rating": 15,
       "capacity": 16000,
       "item_number": "TA-15C-16000-6S1P-EC5",
       "ma_price": "$325.79",
       "list_price": "$325.79"
     },
     {
       "voltage": 6,
       "current_rating": 15,
       "capacity": 16000,
       "item_number": "TA-15C-16000-6S1P-AS150",
       "ma_price": "$325.79",
       "list_price": "$325.79"
     },
     {
       "voltage": 4,
       "current_rating": 25,
       "capacity": 1000,
       "item_number": "TA-25C-10000-4S1P",
       "ma_price": "$149.99",
       "list_price": "$149.99"
     },
     {
       "voltage": 4,
       "current_rating": 25,
       "capacity": 6750,
       "item_number": "TA-25C-6750-4S1P-XT90",
       "ma_price": "$99.00",
       "list_price": "$99.00"
     },
     {
       "voltage": 6,
       "current_rating": 25,
       "capacity": 9000,
       "item_number": "TA-25C-9000-6S1P",
       "ma_price": "$205.62",
       "list_price": "$205.62"
     },
     {
       "voltage": 6,
       "current_rating": 25,
       "capacity": 10000,
       "item_number": "TA-25C-10000-6S1P-AS150",
       "ma_price": "$210.00",
       "list_price": "$210.00"
     },
     {
       "voltage": 4,
       "current_rating": 25,
       "capacity": 22000,
       "item_number": "TA-25C-22000-4S1P",
       "ma_price": "$343.89",
       "list_price": "$343.89"
     },
     {
       "voltage": 6,
       "current_rating": 25,
       "capacity": 22000,
       "item_number": "TA-PLUS-25C-22000-6S1P-AS150",
       "ma_price": "$461.89",
       "list_price": "$461.89"
     },
     {
       "voltage": 6,
       "current_rating": 25,
       "capacity": 22000,
       "item_number": "TA-25C-22000-6S1P-AS150",
       "ma_price": "$461.89",
       "list_price": "$461.89"
     },
     {
       "voltage": 6,
       "current_rating": 35,
       "capacity": 6000,
       "item_number": "TA-35C-6000-6S1P-XT60",
       "ma_price": "$129.99",
       "list_price": "$129.99"
     },
     {
       "voltage": 4,
       "current_rating": 35,
       "capacity": 6600,
       "item_number": "TA-35C-6600-4S2P-XT60",
       "ma_price": "$95.00",
       "list_price": "$95.00"
     }
   ]
  end

  def motors
    @products = [].to_json
  end

  def escs
    @products = [].to_json
  end

  def propellers
    @products = [].to_json
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/batteries.html.erb
<h1>Batteries</h1>
<% @products.each do |battery| %>
  <div class="battery">
    <div>Full Item #: <%= battery[:item_number] %></div>
    <div>Voltage (S): <%= battery[:voltage] %></div>
    <div>Current Rating (C): <%= battery[:current_rating] %></div>
    <div>Capacity (mAh): <%= battery[:capacity] %></div>
    <div>Minimum Advertised Price (USD): <%= battery[:ma_price] %></div>
    <div>Listed Price (USD): <%= battery[:list_price] %></div>
  </div>
<% end %>>

app/views/products/eigen.html.erb
<h1>Eigen</h1>

app/views/products/escs.html.erb
<h1>ESCs</h1>

app/views/products/hamilton.html.erb
<h1>Hamilton</h1>

app/views/products/hammer.html.erb
<h1>Hammer</h1>

app/views/products/hoodlum.html.erb
<h1>Hoodlum</h1>

app/views/products/index.html.erb
<h1>Products</h1>
<%= link_to 'Tango Drones', products_tango_drones_path, class: "products-index"%>
<%= link_to 'Batteries', products_batteries_path, class: "products-index" %>
<%= link_to 'Motors', products_motors_path, class: "products-index" %>
<%= link_to 'ESCs', products_escs_path, class: "products-index" %>
<%= link_to 'Propellers', products_propellers_path, class: "products-index" %>

app/views/products/motors.html.erb
<h1>Motors</h1>

app/views/products/propellers.html.erb
<h1>Propellers</h1>

app/views/products/tango_drones.html.erb
<h1>Tango Drones</h1>
<%= link_to 'Hamilton', products_tango_drones_hamilton_path, class: "products-index"%>
<%= link_to 'Eigen', products_tango_drones_eigen_path, class: "products-index" %>
<%= link_to 'Hoodlum', products_tango_drones_hoodlum_path, class: "products-index" %>
<%= link_to 'Hammer', products_tango_drones_hammer_path, class: "products-index" %>