config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/contact'

  get 'products/index'
  get 'products/tango_drones'
  get 'products/tango_drones/hamilton'
  get 'products/tango_drones/eigen'
  get 'products/tango_drones/hoodlum'
  get 'products/tango_drones/hammer'
  get 'products/batteries'
  get 'products/motors'
  get 'products/escs'
  get 'products/propellers'
  resources :orders

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tango</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Play" rel="stylesheet">
  </head>

  <body>
    <header class="primary-nav container group">
      <h1 class="logo">
        <%= image_tag ("tangoLogo4.png") %>
        <%= link_to "TANGO DRONES", welcome_index_path %>
      </h1>
      <div class='nav nav-options'>
        <%= link_to "Products", products_index_path %>
        <%= link_to "Order" , new_order_path %>
        <%= link_to "Contact", welcome_contact_path %>
      </div>
      </div class='nav-options'>
    </header>
    <div class="container">
      <div class="hero">
        <%= yield %>
      </div>
    </div>
  </body>
</html>